### ISSUE TITLE
hot reload will re-inject icons

### ISSUE THREAD

**Issue by Diolor** [nuxt-community/pwa-module#56]
Hot reload will re-inject the icons in the manifest. I think it's pretty minor but will report it either way.

Reproduce:
- nuxt dev
- reload page
- result:

<img width="1016" alt="screen shot 2018-03-24 at 14 00 58" src="https://user-images.githubusercontent.com/1686807/37864204-d66406da-2f6b-11e8-9fdf-710edb6d35a4.png">

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c32">#c32</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @Diolor. Thanks for the issue report. I tried to locally test the latest versions (PWA and nuxt) and seems this problem is not happening anymore for `nuxt.config` reload. This issue _might_ be because `options.manifest.[icons]` was not cloning after reloads...

Anyway please ping me if you have seen this issue with latest versions again.

Best luck :)
